import { supabase } from '@/integrations/supabase/client';
import type { AIInsight, NewAIInsight, InsightType } from '@/types/phase3';

// ============================================================================
// AI INSIGHTS
// ============================================================================

/**
 * Transform raw DB insight to include UI-friendly fields
 */
function transformInsight(raw: any): AIInsight {
	return {
		...raw,
		// Add UI-friendly aliases
		description: raw.content?.description || raw.content?.summary || raw.title,
		confidence: raw.confidence_score ? Math.round(raw.confidence_score * 100) : null,
	};
}

/**
 * Fetch insights for a proposal
 */
export async function fetchInsights(proposalId: string, type?: InsightType) {
	let query = supabase
		.from('ai_insights')
		.select('*')
		.eq('proposal_id', proposalId)
		.order('generated_at', { ascending: false });

	if (type) {
		query = query.eq('insight_type', type);
	}

	const { data, error } = await query;
	if (error) throw error;
	return (data || []).map(transformInsight) as AIInsight[];
}

/**
 * Fetch insights for all proposals in a team
 * Used by the AI Insights dashboard page
 */
export async function fetchInsightsByTeam(teamId: string, type?: InsightType) {
	// Query ai_insights by joining through proposals to filter by team_id
	let query = supabase
		.from('ai_insights')
		.select(`
			*,
			proposals!inner(team_id)
		`)
		.eq('proposals.team_id', teamId)
		.order('generated_at', { ascending: false });

	if (type) {
		query = query.eq('insight_type', type);
	}

	const { data, error } = await query;
	if (error) throw error;
	
	// Transform and add team_id to each insight
	return (data || []).map((row: any) => ({
		...transformInsight(row),
		team_id: teamId,
	})) as AIInsight[];
}

/**
 * Generate a mock insight for the team (for demo purposes)
 * In production, this would call an Edge Function with Gemini AI
 */
export async function generateInsight(
	teamId: string, 
	proposalId: string | null, 
	insightType: InsightType
): Promise<AIInsight | null> {
	// For now, return null as insights are generated by Edge Functions
	// This is a placeholder for future implementation
	console.log('generateInsight called:', { teamId, proposalId, insightType });
	return null;
}

/**
 * Delete an insight by ID
 */
export async function deleteInsight(id: string) {
	const { error } = await supabase
		.from('ai_insights')
		.delete()
		.eq('id', id);

	if (error) throw error;
}

/**
 * Fetch a single insight by ID
 */
export async function fetchInsightById(id: string) {
	const { data, error } = await supabase
		.from('ai_insights')
		.select('*')
		.eq('id', id)
		.single();

	if (error) throw error;
	return data as AIInsight;
}

/**
 * Create a new AI insight (system-generated)
 * Note: This should typically be called by Edge Functions with service role key
 */
export async function createInsight(insight: NewAIInsight) {
	const { data, error } = await supabase
		.from('ai_insights')
		.insert(insight)
		.select()
		.single();

	if (error) throw error;
	return data as AIInsight;
}

/**
 * Delete expired insights
 */
export async function deleteExpiredInsights(proposalId: string) {
	const now = new Date().toISOString();

	const { error } = await supabase
		.from('ai_insights')
		.delete()
		.eq('proposal_id', proposalId)
		.lt('expires_at', now);

	if (error) throw error;
}

/**
 * Generate insights for a proposal
 * This triggers the Gemini AI analysis
 */
export async function generateInsights(proposalId: string) {
	try {
		// Call the Edge Function to generate insights
		const { data, error } = await supabase.functions.invoke('generate-insights', {
			body: { proposalId },
		});

		if (error) throw error;
		return data;
	} catch (error) {
		console.error('Failed to generate insights:', error);
		throw error;
	}
}

/**
 * Analyze sentiment for a proposal
 */
export async function analyzeSentiment(proposalId: string) {
	const insights = await fetchInsights(proposalId, 'sentiment');

	// Return most recent sentiment, or generate if none exist
	if (insights.length > 0) {
		return insights[0];
	}

	// Trigger generation
	await generateInsights(proposalId);
	const newInsights = await fetchInsights(proposalId, 'sentiment');
	return newInsights[0] || null;
}

/**
 * Predict outcome for a proposal
 */
export async function predictOutcome(proposalId: string) {
	const insights = await fetchInsights(proposalId, 'prediction');

	if (insights.length > 0) {
		return insights[0];
	}

	await generateInsights(proposalId);
	const newInsights = await fetchInsights(proposalId, 'prediction');
	return newInsights[0] || null;
}

/**
 * Detect bias in a proposal
 */
export async function detectBias(proposalId: string) {
	const insights = await fetchInsights(proposalId, 'bias');

	if (insights.length > 0) {
		return insights[0];
	}

	await generateInsights(proposalId);
	const newInsights = await fetchInsights(proposalId, 'bias');
	return newInsights[0] || null;
}

/**
 * Get suggestions for a proposal
 */
export async function getSuggestions(proposalId: string) {
	return fetchInsights(proposalId, 'suggestion');
}

/**
 * Check if insights are stale and need regeneration
 */
export async function areInsightsStale(proposalId: string, maxAgeHours: number = 24): Promise<boolean> {
	const insights = await fetchInsights(proposalId);

	if (insights.length === 0) return true;

	const latestInsight = insights[0];
	const generatedAt = new Date(latestInsight.generated_at);
	const now = new Date();
	const ageHours = (now.getTime() - generatedAt.getTime()) / (1000 * 60 * 60);

	return ageHours > maxAgeHours;
}

/**
 * Refresh insights if stale
 */
export async function refreshInsightsIfStale(proposalId: string) {
	const isStale = await areInsightsStale(proposalId);

	if (isStale) {
		await generateInsights(proposalId);
	}
}
